const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const RiskAssForm = new Schema({
    owner: String,
    admin: String,
    state: String,                   //States include: pending, reviewed and complete
    Location: String,
    assesdate: String,
    assessor: String,
    peer: String,
    title: String,
    people: Number,
    expdate: String,
    activitydesc: String,
    workconditions: String,
    Gname: [String],
    Gcomment: [String],
    GIRC: [String],
    GIRL: [String],
    GIRE: [String],
    GCT: [String],
    Gmeasure: [String],
    GRRC: [String],
    GRRL: [String],
    GRRE: [String],
    Ename: [String],
    Ecomment: [String],
    EIRC: [String],
    EIRL: [String],
    EIRE: [String],
    ECT: [String],
    Emeasure: [String],
    ERRC: [String],
    ERRL: [String],
    ERRE: [String],
    Fname: [String],
    Fcomment: [String],
    FIRC: [String],
    FIRL: [String],
    FIRE: [String],
    FCT: [String],
    Fmeasure: [String],
    FRRC: [String],
    FRRL: [String],
    FRRE: [String],
    Oname: [String],
    Ocomment: [String],
    OIRC: [String],
    OIRL: [String],
    OIRE: [String],
    OCT: [String],
    Omeasure: [String],
    ORRC: [String],
    ORRL: [String],
    ORRE: [String],
    montime: String,
    supname: String,
    supemail: String,
    supdate: String,
    fcname: String,
    fcemail: String,
    fcdate: String,
    headname: String,
    heademail: String,
    headdate: String,
    Gcontrolnum: [String],
    Fcontrolnum: [String],
    Econtrolnum: [String],
    Ocontrolnum: [String],
    comment1: String,
    comment2: String,
    Greview: String,
    Ereview: String,
    Freview: String,
    Oreview: String,
    dateFilled: String,
    forwarded: Number,
    formName: String
});

module.exports = mongoose.model('RiskAssForm', RiskAssForm);
